### ISSUE TITLE
Docker environment

### ISSUE THREAD

**Issue by tabakazu** [tabakazu/taba_blgsmpl#25]
- Docker compose

**Comment by tabakazu** [comment]
https://docs.docker.com/compose/rails/

**Comment by tabakazu** [comment]
**Rails (Ruby + Node.js) Multi-stage Build Dockerfile**
https://github.com/tabakazu/taba_kitchen/blob/master/dockerfiles/rails/Dockerfile

**Comment by tabakazu** [comment]
```yaml
# config/environments/development.rb
username: <%= ENV['DEVELOPMENT_DATABASE_USERNAM'] %>
password: <%= ENV['DEVELOPMENT_DATABASE_PASSWORD'] %>
```
